### PR TITLE
Django and Next.js connection

### PR DESCRIPTION
**Pull request by TheNirmata**
# Description

This PR correlates to #46, #45. 

Implemented the connection between Django and Next.js. Full stack development can be begin with creating mock data. Django by default as a SQLite database. No pseudo code can be found in this PR.  However, documentation for code in this PR will be finished after the submission of this PR. 

## Type of change

- Reorganized files in the app folder (of Next.js). There were duplicated login/sign views. 
- Removed duplicated server files 
- Added serialization.py, urls.py files under routes_apps. 
- Installed _Django Rest Framework_ (DRF) for Django to server as a backend API, i.g. server JSON data to Next.js to consume. 
- `routes_app` folder was created using python CLI to create new functionality to serve data to Next.js
- CORS package was installed to Django to resolve CORS error returned by Next.js

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
- [x] created an API endpoint 'apl/test' to test connection of frontend and server.  Below is the response:
Screenshot 2024-04-26 at 9 44 31 PM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by caglartufan** [comment]
Good work Aimée!

**Review by caglartufan — COMMENTED** [review]
Good work Aimée!
I have some questions though, I think we should ignore __pycache__ folders using .gitignore file.
Also there seem to be 2 interface folders and one of them might be unnecessary I think. One of the folders is located at path LMS/interface and other is located at path LMS/src/interface.

**Comment by caglartufan** [comment]
Something also caught my eye, why is there a separate django folder in root of the project? Could you explain its purpose? Thanks!

**Comment by TheNirmata** [comment]
> Something also caught my eye, why is there a separate django folder in root of the project? Could you explain its purpose? Thanks!

Good question. I am not sure why either that it is still there, I thought I had removed that file. I'll make another PR to make sure that file is removed. But good catch that should not be there

**Comment by TheNirmata** [comment]
> Good work Aimée! I have some questions though, I think we should ignore **pycache** folders using .gitignore file. Also there seem to be 2 interface folders and one of them might be unnecessary I think. One of the folders is located at path LMS/interface and other is located at path LMS/src/interface.



> Good work Aimée! I have some questions though, I think we should ignore **pycache** folders using .gitignore file. Also there seem to be 2 interface folders and one of them might be unnecessary I think. One of the folders is located at path LMS/interface and other is located at path LMS/src/interface.

Thank you for the solution! I also went ahead and deleted the duplicated files. I think this happened when I was running into a merge conflict on my end.

**Pull request merged**
